import { NextResponse } from 'next/server';

export async function GET() {
  const assemblies = [
    {
      id: 1,
      name: 'GCI Central',
      location: 'Nairobi, Kenya',
      address: '123 Main Street, New York, NY 10001',
      service_time: 'Sunday 9:00 AM & 12:00 PM',
      phone: '(+254) 722 707-193',
      email: 'utawala@gospelcentresinternational.org',
      image: '🏛️',
      lat: -1.2921,
      lng: 36.8219
    },
    {
      id: 2,
      name: 'GCI Utawala',
      location: 'Nairobi, Kenya',
      address: 'Utawala Estate, Nairobi - Kenya',
      service_time: 'Sunday 10:00 AM & 6:00 PM',
      phone: '(+254) 722 707-193',
      email: 'utawala@gospelcentresinternational.org',
      image: '⛪',
      lat: -1.2964,
      lng: 36.9458
    },
    {
      id: 3,
      name: 'GCI Kitegela',
      location: 'Nairobi, Kenya',
      address: 'Kitegela Estate, Nairobi - Kenya',
      service_time: 'Sunday 8:30 AM & 10:30 AM',
      phone: '(+254) 722 707-193',
      email: 'utawala@gospelcentresinternational.org',
      image: '✝️',
      lat: -1.2987,
      lng: 36.9432
    },
    {
      id: 4,
      name: 'GCI Siaya',
      location: 'Siaya, Kenya',
      address: 'Siaya County, Kenya',
      service_time: 'Sunday 9:30 AM & 11:30 AM',
      phone: '(+254) 722 707-193',
      email: 'utawala@gospelcentresinternational.org',
      image: '🙏',
      lat: 0.0627,
      lng: 34.2866
    },
    {
      id: 5,
      name: "GCI Got Matar",
      location: "Siaya, Kenya",
      address: "Siaya County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "gotmatar@gospelcentresinternational.org",
      image: "🙏",
      lat: 0.0585,
      lng: 34.2850
    },
    {
      id: 6,
      name: "GCI Kakamega",
      location: "Kakamega, Kenya",
      address: "Kakamega County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "kakamega@gospelcentresinternational.org",
      image: "🙏",
      lat: 0.2827,
      lng: 34.7515
    },
    {
      id: 7,
      name: "GCI Karimba",
      location: "Nairobi, Kenya",
      address: "Utawala Estate, Nairobi - Kenya",
      service_time: "Sunday 10:00 AM & 6:00 PM",
      phone: "(+254) 722 707-193",
      email: "karimba@gospelcentresinternational.org",
      image: "🙏",
      lat: -1.2958,
      lng: 36.9445
    },
    {
      id: 8,
      name: "GCI Meru",
      location: "Meru, Kenya",
      address: "Meru County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "meru@gospelcentresinternational.org",
      image: "🙏",
      lat: 0.0500,
      lng: 37.6500
    },
    {
      id: 9,
      name: "GCI Ngata",
      location: "Nakuru, Kenya",
      address: "Nakuru County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "ngata@gospelcentresinternational.org",
      image: "🙏",
      lat: -0.2833,
      lng: 36.0667
    },
    {
      id: 10,
      name: "GCI Machakos",
      location: "Machakos, Kenya",
      address: "Machakos County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "machakos@gospelcentresinternational.org",
      image: "🙏",
      lat: -1.5167,
      lng: 37.2667
    },
    {
      id: 11,
      name: "GCI Vihiga",
      location: "Vihiga, Kenya",
      address: "Vihiga County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "vihiga@gospelcentresinternational.org",
      image: "🙏",
      lat: 0.0833,
      lng: 34.7167
    },
    {
      id: 12,
      name: "GCI Kipwastuiyo",
      location: "Kericho, Kenya",
      address: "Kericho County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "kipwastuiyo@gospelcentresinternational.org",
      image: "🙏",
      lat: -0.3667,
      lng: 35.2833
    },
    {
      id: 13,
      name: "GCI Marsabit",
      location: "Marsabit, Kenya",
      address: "Marsabit County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "marsabit@gospelcentresinternational.org",
      image: "🙏",
      lat: 2.3333,
      lng: 37.9833
    },
    {
      id: 14,
      name: "GCI Thika Road",
      location: "Kiambu, Kenya",
      address: "Kiambu County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "thikaroad@gospelcentresinternational.org",
      image: "🙏",
      lat: -1.1667,
      lng: 36.8333
    },
    {
      id: 15,
      name: "GCI Homabay",
      location: "Homabay, Kenya",
      address: "Homabay County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "homabay@gospelcentresinternational.org",
      image: "🙏",
      lat: -0.5167,
      lng: 34.4500
    },
    {
      id: 16,
      name: "GCI Mtwapa",
      location: "Kilifi, Kenya",
      address: "Kilifi County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "mtwapa@gospelcentresinternational.org",
      image: "🙏",
      lat: -3.9500,
      lng: 39.7500
    },
    {
      id: 17,
      name: "GCI Maledi",
      location: "Kwale, Kenya",
      address: "Kwale County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "maledi@gospelcentresinternational.org",
      image: "🙏",
      lat: -4.1667,
      lng: 39.4500
    },
    {
      id: 18,
      name: "GCI Huruma",
      location: "Nairobi, Kenya",
      address: "Nairobi County, Kenya",
      service_time: "Sunday 10:00 AM & 6:00 PM",
      phone: "(+254) 722 707-193",
      email: "huruma@gospelcentresinternational.org",
      image: "🙏",
      lat: -1.2750,
      lng: 36.8667
    },
    {
      id: 19,
      name: "GCI Kitale",
      location: "Kitale, Kenya",
      address: "Kitale County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "kitale@gospelcentresinternational.org",
      image: "🙏",
      lat: 1.0167,
      lng: 35.0000
    },
    {
      id: 20,
      name: "GCI Mogotio",
      location: "Baringo, Kenya",
      address: "Baringo County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "mogotio@gospelcentresinternational.org",
      image: "🙏",
      lat: 0.0167,
      lng: 35.9667
    },
    {
      id: 21,
      name: "GCI Kisumu",
      location: "Kisumu, Kenya",
      address: "Kisumu County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "kisumu@gospelcentresinternational.org",
      image: "🙏",
      lat: -0.1022,
      lng: 34.7617
    },
    {
      id: 22,
      name: "GCI Mombasa Road",
      location: "Machakos, Kenya",
      address: "Machakos County, Kenya",
      service_time: "Sunday 9:00 AM & 12:00 PM",
      phone: "(+254) 722 707-193",
      email: "mombasaroad@gospelcentresinternational.org",
      image: "🙏",
      lat: -1.5167,
      lng: 37.2667
    }
  ];

  return NextResponse.json(assemblies);
}